#pragma once

#include <string>
#include <vector>

namespace rgen
{

inline const std::vector<std::string> doxygenConstants = {
    "a",
    "addindex",
    "addtogroup",
    "anchor",
    "arg",
    "attention",
    "author",
    "authors",
    "b",
    "brief",
    "bug",
    "c",
    "callergraph",
    "callgraph",
    "category",
    "cite",
    "class",
    "code",
    "collaborationgraph",
    "concept",
    "cond",
    "copybrief",
    "copydetails",
    "copydoc",
    "copyright",
    "date",
    "def",
    "defgroup",
    "deprecated",
    "details",
    "diafile",
    "dir",
    "directorygraph",
    "docbookinclude",
    "docbookonly",
    "dontinclude",
    "dot",
    "dotfile",
    "doxyconfig",
    "e",
    "else",
    "elseif",
    "em",
    "emoji",
    "endcode",
    "endcond",
    "enddocbookonly",
    "enddot",
    "endhtmlonly",
    "endif",
    "endinternal",
    "endlatexonly",
    "endlink",
    "endmanonly",
    "endmsc",
    "endparblock",
    "endrtfonly",
    "endsecreflist",
    "endverbatim",
    "enduml",
    "endxmlonly",
    "enum",
    "example",
    "exception",
    "extends",
    "f(",
    "f)",
    "f$",
    "f[",
    "f]",
    "f{",
    "f}",
    "file",
    "fileinfo",
    "fn",
    "groupgraph",
    "headerfile",
    "hidecallergraph",
    "hidecallgraph",
    "hidecollaborationgraph",
    "hidedirectorygraph",
    "hidegroupgraph",
    "hideincludedbygraph",
    "hideincludegraph",
    "hiderefby",
    "hiderefs",
    "hideinitializer",
    "htmlinclude",
    "htmlonly",
    "idlexcept",
    "if",
    "ifnot",
    "image",
    "implements",
    "include",
    "includedoc",
    "includedbygraph",
    "includegraph",
    "includelineno",
    "ingroup",
    "internal",
    "invariant",
    "interface",
    "latexinclude",
    "latexonly",
    "li",
    "line",
    "lineinfo",
    "link",
    "mainpage",
    "maninclude",
    "manonly",
    "memberof",
    "module",
    "msc",
    "mscfile",
    "n",
    "name",
    "namespace",
    "noop",
    "nosubgrouping",
    "note",
    "overload",
    "p",
    "package",
    "page",
    "par",
    "paragraph",
    "param",
    "parblock",
    "post",
    "pre",
    "private",
    "privatesection",
    "property",
    "protected",
    "protectedsection",
    "protocol",
    "public",
    "publicsection",
    "pure",
    "qualifier",
    "raisewarning",
    "ref",
    "refitem",
    "related",
    "relates",
    "relatedalso",
    "relatesalso",
    "remark",
    "remarks",
    "result",
    "return",
    "returns",
    "retval",
    "rtfinclude",
    "rtfonly",
    "sa",
    "secreflist",
    "section",
    "see",
    "short",
    "showdate",
    "showinitializer",
    "showrefby",
    "showrefs",
    "since",
    "skip",
    "skipline",
    "snippet",
    "snippetdoc",
    "snippetlineno",
    "static",
    "startuml",
    "struct",
    "subpage",
    "subsection",
    "subsubsection",
    "tableofcontents",
    "test",
    "throw",
    "throws",
    "todo",
    "tparam",
    "typedef",
    "union",
    "until",
    "var",
    "verbatim",
    "verbinclude",
    "version",
    "vhdlflow",
    "warning",
    "weakgroup",
    "xmlinclude",
    "xmlonly",
    "xrefitem",
    // "$",
    // "@",
    // R"(\)",
    // "&",
    // "~",
    // "<",
    // "=",
    // ">",
    // "#",
    // "%",
    // R"(")",
    // ",",
    // ".",
    // "::",
    // "|",
    // "--",
    // "---",
};

}
